In [61]:
from uu import encode

import pandas as pd
import numpy as np
import seaborn as sns

In [62]:
df=pd.read_csv("encoding_practice_data.csv")
df.head()

   Employee_ID  Department Seniority_Level Remote_Work  Monthly_Hours
0          101       Sales          Junior         Yes            188
1          102  Management          Junior         Yes            178
2          103  Management          Senior          No            164
3          104  Management          Senior         Yes            192
4          105  Management          Junior          No            157

In [63]:
df["Seniority_Level"].unique()

array(['Junior', 'Senior', 'Mid'], dtype=object)

In [64]:
df["Department"].unique()

array(['Sales', 'Management', 'Data Science', 'Marketing', 'Dev', 'QA'],
      dtype=object)

In [65]:
df["Remote_Work"].unique()

array(['Yes', 'No'], dtype=object)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      200 non-null    int64
 1   Department       200 non-null    object
 2   Seniority_Level  200 non-null    object
 3   Remote_Work      200 non-null    object
 4   Monthly_Hours    200 non-null    int64
dtypes: int64(2), object(3)
memory usage: 7.9+ KB

In [67]:
df.isna().sum()

Employee_ID        0
Department         0
Seniority_Level    0
Remote_Work        0
Monthly_Hours      0
dtype: int64

In [68]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
encode_data=ohe.fit_transform(df[["Department"]])

In [69]:
encode_data

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.]], shape=(200, 6))

In [70]:
encoded_df=pd.DataFrame(encode_data,columns=ohe.get_feature_names_out(["Department"]))

In [71]:
encoded_df

,Department_Data Science,Department_Dev,Department_Management,Department_Marketing,Department_QA,Department_Sales
0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...
195,0.0,0.0,1.0,0.0,0.0,0.0
196,0.0,0.0,0.0,0.0,1.0,0.0
197,0.0,1.0,0.0,0.0,0.0,0.0
198,0.0,0.0,0.0,0.0,1.0,0.0
199,0.0,1.0,0.0,0.0,0.0,0.0

In [72]:
seniority_map={"Junior":3,"Mid":2,"Senior":1}

In [73]:
df["Seniority_Level"]= df["Seniority_Level"].map(seniority_map)

In [74]:
df

     Employee_ID  Department  Seniority_Level Remote_Work  Monthly_Hours
0            101       Sales                3         Yes            188
1            102  Management                3         Yes            178
2            103  Management                1          No            164
3            104  Management                1         Yes            192
4            105  Management                3          No            157
..           ...         ...              ...         ...            ...
195          296  Management                3          No            188
196          297          QA                3          No            155
197          298         Dev                2          No            157
198          299          QA                1         Yes            176
199          300         Dev                3         Yes            158

[200 rows x 5 columns]

In [91]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Remote_Work"]=le.fit_transform(df["Remote_Work"])

In [92]:
print(f"Classes found: {le.classes_}")

Classes found: ['No' 'Yes']

In [93]:
df_final = pd.concat([df.drop('Department', axis=1), encoded_df], axis=1)

In [94]:
df_final

,Employee_ID,Seniority_Level,Remote_Work,Monthly_Hours,remote_work,Department_Data Science,Department_Dev,Department_Management,Department_Marketing,Department_QA,Department_Sales
0,101,3,1,188,1,0.0,0.0,0.0,0.0,0.0,1.0
1,102,3,1,178,1,0.0,0.0,1.0,0.0,0.0,0.0
2,103,1,0,164,0,0.0,0.0,1.0,0.0,0.0,0.0
3,104,1,1,192,1,0.0,0.0,1.0,0.0,0.0,0.0
4,105,3,0,157,0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
195,296,3,0,188,0,0.0,0.0,1.0,0.0,0.0,0.0
196,297,3,0,155,0,0.0,0.0,0.0,0.0,1.0,0.0
197,298,2,0,157,0,0.0,1.0,0.0,0.0,0.0,0.0
198,299,1,1,176,1,0.0,0.0,0.0,0.0,1.0,0.0
199,300,3,1,158,1,0.0,1.0,0.0,0.0,0.0,0.0

In [95]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Employee_ID              200 non-null    int64
 1   Seniority_Level          200 non-null    int64
 2   Remote_Work              200 non-null    int64
 3   Monthly_Hours            200 non-null    int64
 4   remote_work              200 non-null    int64
 5   Department_Data Science  200 non-null    float64
 6   Department_Dev           200 non-null    float64
 7   Department_Management    200 non-null    float64
 8   Department_Marketing     200 non-null    float64
 9   Department_QA            200 non-null    float64
 10  Department_Sales         200 non-null    float64
dtypes: float64(6), int64(5)
memory usage: 17.3 KB