In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("overfitting_classification_dataset.csv")
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,customer_id,leak_feature,target
0,1.054859,-1.084210,-6.237457,0.256222,-0.130737,-0.840607,0.066593,-1.681577,1.104942,2.116747,...,-0.514949,-0.320560,0.154048,0.558651,1.017686,-3.451998,-1.158286,1000,0.004414,0
1,0.371404,-1.225488,6.459929,2.391920,-1.039634,0.027256,-0.774462,0.266700,0.421085,-0.840060,...,0.911027,1.093123,-0.278709,-0.456497,1.019777,2.914809,0.758944,1001,0.993243,1
2,0.007964,-1.105353,1.054154,1.027422,-0.226261,0.843373,0.728685,0.889916,0.756053,0.782183,...,1.981692,1.369709,-0.272975,0.872919,-0.278391,-0.622246,-0.738803,1002,1.023541,1
3,2.013699,-0.821485,6.060211,1.225471,-0.297057,-1.500468,-1.815542,-0.656430,-0.300872,-0.169820,...,-0.668876,-0.746848,-1.609521,0.677209,0.822717,2.943926,-0.260175,1003,1.001563,1
4,1.769862,-0.647241,-2.889853,-1.830768,1.188146,-0.628485,1.309473,0.094994,0.536744,-0.058882,...,-0.191821,-0.510436,1.038389,0.632962,-0.295541,2.937227,-1.446128,1004,0.003879,0

In [3]:
df.isnull().sum()

feature_0       0
feature_1       0
feature_2       0
feature_3       0
feature_4       0
               ..
feature_58      0
feature_59      0
customer_id     0
leak_feature    0
target          0
Length: 63, dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.describe()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,customer_id,leak_feature,target
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,...,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,-0.028889,-0.003295,-0.117183,-0.013836,-0.059055,0.033959,-0.180940,-0.002413,-0.127934,0.092840,...,0.026552,0.071758,-0.001967,-0.016892,0.049957,0.368198,-0.011736,1059.500000,0.494138,0.491667
std,1.000081,1.030949,4.358169,1.084078,1.041979,1.095636,1.042321,0.981580,0.935222,0.921669,...,0.995443,1.066102,0.965652,1.049579,0.928806,2.307749,0.991001,34.785054,0.502603,0.502027
min,-3.324756,-2.989393,-7.818070,-2.563954,-3.254479,-2.722278,-3.071151,-2.276991,-2.492343,-2.140266,...,-2.622219,-2.230330,-1.989816,-2.604347,-2.269498,-6.388784,-2.230320,1000.000000,-0.045165,0.000000
25%,-0.620143,-0.651883,-2.776948,-0.887771,-0.768619,-0.624634,-0.732820,-0.682434,-0.658799,-0.398032,...,-0.515863,-0.595624,-0.544276,-0.793594,-0.601772,-1.086700,-0.689634,1029.750000,0.003484,0.000000
50%,0.068496,-0.008604,-0.911085,-0.077716,0.008102,-0.003421,-0.157400,-0.095957,-0.027530,0.055299,...,-0.059195,0.085680,-0.074445,0.093641,0.044243,0.822374,0.095609,1059.500000,0.036945,0.000000
75%,0.575823,0.593809,3.750579,0.780777,0.524794,0.639772,0.503700,0.585048,0.440870,0.681499,...,0.516234,0.871980,0.574772,0.821289,0.681049,2.660997,0.680298,1089.250000,1.000861,1.000000
max,2.569927,2.511540,7.317072,2.594310,3.089890,3.014712,2.551174,2.937753,2.182507,2.540391,...,2.278402,2.437243,2.357376,2.238353,2.965010,3.457624,2.374142,1119.000000,1.044737,1.000000

In [6]:
df.drop("customer_id",axis=1,inplace=True)
df.drop("leak_feature",axis=1,inplace=True)

In [7]:
df

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,target
0,1.054859,-1.084210,-6.237457,0.256222,-0.130737,-0.840607,0.066593,-1.681577,1.104942,2.116747,...,3.428018,0.098498,-0.514949,-0.320560,0.154048,0.558651,1.017686,-3.451998,-1.158286,0
1,0.371404,-1.225488,6.459929,2.391920,-1.039634,0.027256,-0.774462,0.266700,0.421085,-0.840060,...,-4.497641,0.358207,0.911027,1.093123,-0.278709,-0.456497,1.019777,2.914809,0.758944,1
2,0.007964,-1.105353,1.054154,1.027422,-0.226261,0.843373,0.728685,0.889916,0.756053,0.782183,...,-4.753879,1.125588,1.981692,1.369709,-0.272975,0.872919,-0.278391,-0.622246,-0.738803,1
3,2.013699,-0.821485,6.060211,1.225471,-0.297057,-1.500468,-1.815542,-0.656430,-0.300872,-0.169820,...,-4.477764,1.131578,-0.668876,-0.746848,-1.609521,0.677209,0.822717,2.943926,-0.260175,1
4,1.769862,-0.647241,-2.889853,-1.830768,1.188146,-0.628485,1.309473,0.094994,0.536744,-0.058882,...,5.444136,-0.005397,-0.191821,-0.510436,1.038389,0.632962,-0.295541,2.937227,-1.446128,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0.969041,0.723348,5.024322,-0.276011,-0.314415,1.126348,-0.706129,1.880804,-1.595567,1.645382,...,-2.566374,-1.135105,-0.116764,0.600938,-0.824485,0.514048,0.401464,2.683191,-2.230320,1
116,-0.392942,0.459781,-7.453730,-1.741704,-0.675814,-1.329185,0.010879,-1.107942,-1.571578,-0.174820,...,6.454176,0.734598,0.149356,0.975678,0.677182,-0.765810,-0.249810,-6.388784,-0.097831,0
117,0.331485,-1.046355,-4.808120,0.091101,0.378811,0.989860,-1.344649,-0.426269,0.377829,0.029103,...,2.982749,1.049994,0.314706,0.340654,0.338892,1.341432,-0.023025,-1.498069,0.816868,0
118,0.151878,0.654677,0.370771,-0.327824,-0.840471,2.350206,-2.248143,-0.692152,-0.224746,-0.473265,...,-4.388927,-1.151868,0.344356,-1.764596,-0.715022,0.014244,1.370410,-0.663575,1.507634,1
119,0.344384,-0.241750,2.269537,-0.171948,1.698093,-0.630219,0.608442,-0.548749,-0.865071,0.780070,...,-4.978972,-2.370252,-0.859500,-0.269017,0.252167,-0.373662,0.083481,0.343141,0.635662,1

In [8]:
x=df.drop(columns = "target",axis=1)
y=df["target"]

In [9]:
x

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59
0,1.054859,-1.084210,-6.237457,0.256222,-0.130737,-0.840607,0.066593,-1.681577,1.104942,2.116747,...,-2.334571,3.428018,0.098498,-0.514949,-0.320560,0.154048,0.558651,1.017686,-3.451998,-1.158286
1,0.371404,-1.225488,6.459929,2.391920,-1.039634,0.027256,-0.774462,0.266700,0.421085,-0.840060,...,3.291849,-4.497641,0.358207,0.911027,1.093123,-0.278709,-0.456497,1.019777,2.914809,0.758944
2,0.007964,-1.105353,1.054154,1.027422,-0.226261,0.843373,0.728685,0.889916,0.756053,0.782183,...,2.670341,-4.753879,1.125588,1.981692,1.369709,-0.272975,0.872919,-0.278391,-0.622246,-0.738803
3,2.013699,-0.821485,6.060211,1.225471,-0.297057,-1.500468,-1.815542,-0.656430,-0.300872,-0.169820,...,2.966352,-4.477764,1.131578,-0.668876,-0.746848,-1.609521,0.677209,0.822717,2.943926,-0.260175
4,1.769862,-0.647241,-2.889853,-1.830768,1.188146,-0.628485,1.309473,0.094994,0.536744,-0.058882,...,-6.348574,5.444136,-0.005397,-0.191821,-0.510436,1.038389,0.632962,-0.295541,2.937227,-1.446128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0.969041,0.723348,5.024322,-0.276011,-0.314415,1.126348,-0.706129,1.880804,-1.595567,1.645382,...,1.916379,-2.566374,-1.135105,-0.116764,0.600938,-0.824485,0.514048,0.401464,2.683191,-2.230320
116,-0.392942,0.459781,-7.453730,-1.741704,-0.675814,-1.329185,0.010879,-1.107942,-1.571578,-0.174820,...,-1.352545,6.454176,0.734598,0.149356,0.975678,0.677182,-0.765810,-0.249810,-6.388784,-0.097831
117,0.331485,-1.046355,-4.808120,0.091101,0.378811,0.989860,-1.344649,-0.426269,0.377829,0.029103,...,-2.969448,2.982749,1.049994,0.314706,0.340654,0.338892,1.341432,-0.023025,-1.498069,0.816868
118,0.151878,0.654677,0.370771,-0.327824,-0.840471,2.350206,-2.248143,-0.692152,-0.224746,-0.473265,...,2.106041,-4.388927,-1.151868,0.344356,-1.764596,-0.715022,0.014244,1.370410,-0.663575,1.507634
119,0.344384,-0.241750,2.269537,-0.171948,1.698093,-0.630219,0.608442,-0.548749,-0.865071,0.780070,...,2.731381,-4.978972,-2.370252,-0.859500,-0.269017,0.252167,-0.373662,0.083481,0.343141,0.635662

In [10]:
y

0      0
1      1
2      1
3      1
4      0
      ..
115    1
116    0
117    0
118    1
119    1
Name: target, Length: 120, dtype: int64

In [11]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
best_score = 0
best_model = None
best_k = None

for K in [1,3,5,7,9,11]:

    knn = KNeighborsClassifier(n_neighbors=K)
    knn.fit(X_train, y_train)

    prediction = knn.predict(X_test)

    score = accuracy_score(y_test, prediction)

    print(K, "=", score)

    if score > best_score:
        best_score = score
        best_model = knn
        best_k = K

1 = 0.8611111111111112
3 = 0.8611111111111112
5 = 0.9166666666666666
7 = 0.9166666666666666
9 = 0.9444444444444444
11 = 0.9444444444444444

In [18]:
print("Best K:", best_k)

train_score = best_model.score(X_train, y_train)
test_score = best_model.score(X_test, y_test)

print("Train:", train_score)
print("Test:", test_score)

Best K: 9
Train: 0.9880952380952381
Test: 0.9444444444444444

In [19]:
from sklearn.model_selection import cross_val_score

# 5-fold cross-validation
scores = cross_val_score(knn, x, y, cv=5)
print(f"Average CV Score: {scores.mean():.4f}")

Average CV Score: 0.9833

In [21]:
#main method to use this

from sklearn.model_selection import GridSearchCV

paramgrid = {"n_neighbors": np.arange(1,31)}
knn_gscv = GridSearchCV(KNeighborsClassifier(), param_grid=paramgrid, cv=5)
knn_gscv.fit(x,y)
print(f"Optimal K is: {knn_gscv.best_params_['n_neighbors']}")

Optimal K is: 1

In [22]:
# Calculate both scores
train_score = knn.score(X_train, y_train)
test_score = knn.score(X_test, y_test)

print(f"Training Accuracy: {train_score:.4f}")
print(f"Testing Accuracy: {test_score:.4f}")

Training Accuracy: 0.9643
Testing Accuracy: 0.9444